builders:
  themedColorPaletteGeneratorBuilder:
    import: "package:themed_color_palette/themed_color_palette.dart"
    builder_factories: ["themedColorPaletteGeneratorBuilder"]
    build_extensions: { ".theme.yaml": [".theme.g.dart"] }
    build_to: source
    auto_apply: dependents
