name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Code Analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        # cSpell:ignore subosito
        uses: subosito/flutter-action@v1
      - run: flutter pub get
      - name: Analyze dart code
        uses: ValentinVignal/action-dart-analyze@v0.12
      - name: Run the tests
        if: always()
        run: flutter test
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
