on: [pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Code Analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: flutter pub get
      - name: Analyze dart code
        uses: ValentinVignal/action-dart-analyze@v0.12
      - name: Run the tests
        run: flutter test
